"""
process-document custom skill.

One call per source PDF. Fetches the PDF from blob, calls Azure Document
Intelligence directly, extracts:

  - per-figure cropped images + bbox + caption + headers + surrounding context
  - per-table markdown (with multi-page merging + oversized splits)

Returns two arrays the skillset projects as peer records:
  - enriched_figures
  - enriched_tables

The vision call still runs separately (per figure) in the analyze-diagram
skill so we can keep batching/parallelism tunable from the skillset.
"""

import logging
from typing import Any

from .di_client import (
    fetch_cached_analysis,
    fetch_cached_crop,
    fetch_precomputed_output,
)
from .ids import (
    SKILL_VERSION,
    parent_id_for,
    safe_str,
)
from .sections import (
    build_section_index,
    extract_surrounding_text,
    find_section_for_page,
    find_section_for_page_range,
)
from .tables import extract_table_records


def _figure_first_page(figure: dict[str, Any]) -> int:
    for br in figure.get("boundingRegions", []) or []:
        pn = br.get("pageNumber")
        if isinstance(pn, int):
            return pn
    return 0


def _figure_polygon(figure: dict[str, Any]) -> list[float]:
    for br in figure.get("boundingRegions", []) or []:
        poly = br.get("polygon")
        if poly:
            return poly
    return []


def _figure_caption(figure: dict[str, Any]) -> str:
    cap = figure.get("caption") or {}
    return (cap.get("content") or "").strip()


def process_document(data: dict[str, Any]) -> dict[str, Any]:
    source_file = safe_str(data.get("source_file"))
    source_path = safe_str(data.get("source_path"))
    parent_id = parent_id_for(source_path, source_file)

    if not source_path:
        return {
            "enriched_figures": [],
            "enriched_tables": [],
            "processing_status": "no_source_path",
            "skill_version": SKILL_VERSION,
        }

    # Fast path: if a pre-computed output blob exists (generated by
    # preanalyze.py), return it directly. This avoids loading the large
    # DI result and fetching thousands of crop blobs at runtime.
    precomputed = fetch_precomputed_output(source_path)
    if precomputed is not None:
        logging.info("using pre-computed output for %s", source_file)
        precomputed["skill_version"] = SKILL_VERSION
        return precomputed

    # Check for pre-analyzed DI cache (written by scripts/preanalyze.py).
    # Without it, a live DI call would time out on any large PDF and tie
    # up a skill invocation for up to 230 seconds, so we fail fast and
    # tell the operator what to do.
    cache_data = fetch_cached_analysis(source_path)
    if cache_data is None:
        logging.warning(
            "preanalyze cache missing for %s; skipping without calling live DI. "
            "Run scripts/preanalyze.py --incremental then reset+run the indexer.",
            source_file,
        )
        return {
            "enriched_figures": [],
            "enriched_tables": [],
            "processing_status": "needs_preanalyze",
            "skill_version": SKILL_VERSION,
        }
    logging.info("using cached DI result for %s", source_file)
    analyze = cache_data["analyzeResult"]

    # Total physical page count of the source PDF, derived from DI's
    # `pages[]` array. Embedded into every enriched figure / table dict
    # and emitted as a top-level output so downstream skills (analyze-
    # diagram, shape-table, build-doc-summary) can stamp it on every
    # record without re-fetching the cache.
    pages_array = analyze.get("pages") or []
    pdf_total_pages = len(pages_array) if pages_array else None

    sections_index = build_section_index(analyze)

    enriched_figures: list[dict[str, Any]] = []
    skipped_no_polygon = 0
    skipped_no_crop = 0
    di_figure_count = len(analyze.get("figures", []) or [])
    for fig_idx, figure in enumerate(analyze.get("figures", []) or []):
        page = _figure_first_page(figure)
        polygon = _figure_polygon(figure)
        figure_id = figure.get("id") or f"fig_{fig_idx}"
        if not page or not polygon:
            # Silent skips hide data loss. Log each and summarize at end.
            skipped_no_polygon += 1
            logging.info("skip figure %s (no page=%s or polygon=%s)",
                         figure_id, bool(page), bool(polygon))
            continue
        caption = _figure_caption(figure)

        # Fetch pre-cropped image from the blob cache. The live-crop
        # fallback was removed together with the live-DI fallback: if the
        # DI cache exists but this specific crop does not, there's nothing
        # to analyze and we skip the figure with a clear log.
        crop_data = fetch_cached_crop(source_path, figure_id)
        if crop_data is None:
            skipped_no_crop += 1
            logging.warning(
                "crop cache missing for %s fig %s; skipping (re-run preanalyze to rebuild)",
                source_file, figure_id,
            )
            continue
        image_b64 = crop_data["image_b64"]
        bbox = crop_data["bbox"]

        section = find_section_for_page(sections_index, page)
        h1 = section["header_1"] if section else ""
        h2 = section["header_2"] if section else ""
        h3 = section["header_3"] if section else ""
        # 400 chars before + 400 after the caption gives the diagram's
        # vision prompt and chunk_for_semantic enough procedural context
        # to ground the figure (typical: "after de-energizing per
        # Section 4.1, locate the relay shown in Figure 18.117 and ..."
        # — needs more than 200 chars to capture meaningfully).
        surrounding = (
            extract_surrounding_text(section["content"], caption, chars=400)
            if section else ""
        )

        enriched_figures.append({
            "figure_id": figure_id,
            "page_number": page,
            "caption": caption,
            "image_b64": image_b64,
            "bbox": bbox,
            "header_1": h1,
            "header_2": h2,
            "header_3": h3,
            "surrounding_context": surrounding,
            "source_file": source_file,
            "source_path": source_path,
            "parent_id": parent_id,
            "pdf_total_pages": pdf_total_pages,
        })

    enriched_tables: list[dict[str, Any]] = []
    for tbl in extract_table_records(analyze):
        # Use the table's full page range when picking the section, not
        # just page_start. A multi-page table that begins at the bottom
        # of one section's last page and continues into the next section
        # should inherit the section that contains the *bulk* of its
        # content, not the section that happens to start at page_start.
        section = find_section_for_page_range(
            sections_index, tbl["page_start"], tbl.get("page_end")
        )
        h1 = section["header_1"] if section else ""
        h2 = section["header_2"] if section else ""
        h3 = section["header_3"] if section else ""
        enriched_tables.append({
            "table_index": tbl["index"],
            "table_rows": tbl.get("table_rows", []),
            "page_start": tbl["page_start"],
            "page_end": tbl["page_end"],
            "markdown": tbl["markdown"],
            "row_count": tbl["row_count"],
            "col_count": tbl["col_count"],
            "caption": tbl["caption"],
            "bboxes": tbl.get("bboxes", []),
            "header_1": h1,
            "header_2": h2,
            "header_3": h3,
            "source_file": source_file,
            "source_path": source_path,
            "parent_id": parent_id,
            "pdf_total_pages": pdf_total_pages,
        })

    if skipped_no_polygon:
        logging.info("process_document %s: skipped %d figures with no polygon/page",
                     source_file, skipped_no_polygon)

    # Surface visibility on figure/table loss so operators have a quantitative
    # signal beyond grep-the-logs. The status string switches to a non-ok
    # tag when material loss occurred — the indexer status page and any
    # downstream monitoring keyed on `processing_status` immediately
    # surface "this PDF lost N figures" without requiring log-mining.
    di_table_count = len(enriched_tables)
    figures_dropped = skipped_no_polygon + skipped_no_crop
    figures_kept = len(enriched_figures)
    status = "ok"
    if di_figure_count > 0 and figures_kept == 0:
        # Catastrophic: DI saw figures, we emitted none. Crop-cache rot or
        # systematic preanalyze failure on this PDF.
        status = "all_figures_dropped"
    elif figures_dropped > 0 and figures_dropped >= max(5, di_figure_count // 4):
        # Material loss: ≥25% of DI's figures didn't survive. Worth alerting.
        status = "partial_figure_loss"

    logging.info(
        "process_document %s: figures DI=%d kept=%d dropped=%d (no_polygon=%d, no_crop=%d) tables=%d status=%s",
        source_file, di_figure_count, figures_kept, figures_dropped,
        skipped_no_polygon, skipped_no_crop, di_table_count, status,
    )

    return {
        "enriched_figures": enriched_figures,
        "enriched_tables": enriched_tables,
        "pdf_total_pages": pdf_total_pages,
        "processing_status": status,
        "di_figure_count": di_figure_count,
        "figures_kept_count": figures_kept,
        "figures_dropped_count": figures_dropped,
        "tables_count": di_table_count,
        "skill_version": SKILL_VERSION,
    }
